site_name: Supervision
site_url: https://supervision.roboflow.com/
site_author: Roboflow
site_description: A set of easy-to-use utilities that will come in handy in any computer vision project.
repo_name: roboflow/supervision
repo_url: https://github.com/roboflow/supervision
edit_uri: https://github.com/roboflow/supervision/tree/main/docs
copyright: Roboflow 2024. All rights reserved.

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/roboflow
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/roboflow
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/roboflow-ai/mycompany/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/roboflow
  analytics:
    provider: google
    property: G-P7ZG0Y19G5
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - How to:
      - Detect and Annotate: how_to/detect_and_annotate.md
      - Track Objects: how_to/track_objects.md
      - Filter Detections: how_to/filter_detections.md
  - API:
    - Classifications:
        - Core: classification/core.md
    - Detections:
        - Core: detection/core.md
        - Utils: detection/utils.md
    - Tools:
        - Line Zone: detection/tools/line_zone.md
        - Polygon Zone: detection/tools/polygon_zone.md
        - Inference Slicer: detection/tools/inference_slicer.md
        - Detection Smoother: detection/tools/smoother.md
    - Annotators: annotators.md
    - Trackers: trackers.md
    - Datasets: datasets.md
    - Metrics:
      - Object Detection: metrics/detection.md
    - Draw:
        - Color: draw/color.md
        - Utils: draw/utils.md
    - Utils:
        - Video: utils/video.md
        - Image: utils/image.md
        - Notebook: utils/notebook.md
        - File: utils/file.md
  - Assets: assets.md
  - Changelog:
        - Changelog: changelog.md
        - Deprecated: deprecated.md

theme:
  name: 'material'
  logo: assets/supervision-lenny.png
  favicon: assets/supervision-lenny.png
  custom_dir: docs/theme
  palette:
    # Palette for light mode
    - scheme: default
      primary: 'custom'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: 'custom'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - content.code.annotate

plugins:
  - mkdocstrings
  - mike:
      canonical_version: latest

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - "https://widget.kapa.ai/kapa-widget.bundle.js"
  - "javascript/init_kapa_widget.js"
